---
- hosts: all
  gather_facts: False
  connection: network_cli

  vars:
    password: cisco

  tasks:
      - name: Change Host name
        cisco.ios.ios_hostname:
          config:
            hostname: "aws-c9800"
          state: merged

      - name: run show version on remote devices
        cisco.ios.ios_command:
          commands: 
          - show version
        register: out

      - name: Configure Commands
        cisco.ios.ios_command:
          commands: 
          - configure terminal
          - aaa new-model
          - aaa authentication login default local
          - aaa authorization exec default local 
          - aaa session-id common
          - username Netconf privilege 15 password 0 netconf
          - username Restconf privilege 15 password 0 restconf
          - nmsp enable
          - netconf-yang
          - ip http authentication local
          - ip http secure-server 
          - ntp server au.pool.ntp.org
          - ip http server
          - ip route 0.0.0.0 0.0.0.0 10.0.10.1
          - wireless country AU
          - wlan CiscoLiveTest 1 CiscoLiveTest
          - security wpa psk set-key ascii 0 cisco1234
          - no shutdown
          - interface g1
          - wireless management interface g1
          - end
          - wireless config vwlc-ssc key-size 2048 signature-algo sha256 password 0 cisco123
        register: out 

      - name: Save running to startup when modified
        cisco.ios.ios_config:
          save_when: modified

      - name: get timestamp
        command: date +%Y%m%d
        register: timestamp

      - name: Configurable backup path
        cisco.ios.ios_config:
          backup: true
          backup_options:
            filename: "{{ inventory_hostname }}-backup-{{ timestamp.stdout }}.txt"
            dir_path: /Users/mrebetzk/Documents/Projects/cisco_ansible_WIRELESS/backups
